# Generated by Django 3.1.4 on 2020-12-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='create',
            new_name='created',
        ),
    ]
