# Generated by Django 3.1.4 on 2020-12-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201228_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
    ]
