# Generated by Django 3.1.4 on 2020-12-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20201229_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, height_field=200, upload_to='images/', verbose_name='Изображение', width_field=200),
        ),
    ]
