# Generated by Django 3.1.4 on 2020-12-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20201229_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
