# Generated by Django 3.1.4 on 2020-12-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20201229_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='images/', verbose_name='Изображение', width_field='image_width'),
        ),
    ]
