# Generated by Django 3.1.4 on 2020-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20201229_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='400', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='400', editable=False, null=True),
        ),
    ]
